import test from 'node:test';
import assert from 'node:assert/strict';
import {sample,empty,validate,derive,score,parseCSV,parseInput,toCSV,csvCell,memo,FIELDS} from '../../site/assets/risk-core.mjs';
test('vendor AI and privacy flags propagate to AI, ERM and assurance',()=>{const w=sample();const before=derive(w);w.records[1].ai=true;w.records[1].approved=false;const after=derive(validate(w));assert.equal(after.ai,before.ai+1);assert.equal(after.aiReviews,before.aiReviews+1);assert.ok(after.rows[1].priority>before.rows[1].priority);w.records[1].evidence='failed';assert.equal(derive(w).ready,before.ready-1);});
test('AI evaluation failures hold release gate and drive correct denominator',()=>{const w=sample();let r=derive(w).rows[2];assert.equal(r.releaseReady,true);assert.equal(r.evalFailureRate,0);w.records[2].aiEvalFailed=3;r=derive(w).rows[2];assert.equal(r.releaseReady,false);assert.equal(r.evalFailureRate,10);assert.equal(r.aiReview,true);w.records[2].aiEvalTotal=0;assert.throws(()=>validate(w),/cannot exceed/);});
test('expiry applies at explicit snapshot and collector error is not fail',()=>{const w=sample();w.asOf='2027-01-01';const d=derive(w);assert.equal(d.current,0);assert.equal(d.ready,0);assert.equal(d.rows[1].effectiveEvidence,'stale');assert.equal(d.rows[4].effectiveEvidence,'error');assert.equal(d.rows[4].evidenceCredit,0);});
test('evidence flag without passing control test does not earn score credit',()=>{const w=sample();w.records[1].testOutcome='not-tested';assert.equal(score(w.records[1]).evidenceCredit,0);assert.equal(score(w.records[1]).answerReady,false);});
test('linked dependency concentration and invalid graphs',()=>{const w=sample();assert.equal(derive(w).dependencyCounts.V05,2);w.records[4].parentVendorId='V01';assert.throws(()=>validate(w),/cycle/);w.records[4].parentVendorId='UNKNOWN';assert.throws(()=>validate(w),/existing record/);});
test('JSON roundtrip preserves state and no extra record payload allowed',()=>{const w=sample();assert.deepEqual(parseInput(JSON.stringify(w),'workspace.json'),w);w.records[0].rawPrompt='secret';assert.throws(()=>validate(w),/unsupported field/);});
test('CSV handles commas, quotes and multiline cells exactly',()=>{const w=sample();w.records[0].name='Supplier, "quoted"';w.records[0].rationale='One line\nAnother line';assert.deepEqual(parseCSV(toCSV(w.records)).records,w.records);assert.throws(()=>parseCSV('"unterminated'),/Unclosed/);assert.throws(()=>parseCSV('id,name\na,b'),/header/);});
test('formula injection export protected without changing JSON source',()=>{for(const v of ['=1+1','+cmd','-1','@SUM(A1)',' \t=2'])assert.ok(csvCell(v).startsWith('"\''));const w=sample();w.records[0].name='=HYPERLINK("https://invalid")';assert.equal(JSON.parse(JSON.stringify(w)).records[0].name,w.records[0].name);assert.ok(toCSV(w.records).includes("'=HYPERLINK"));});
test('empty denominator and zero setup return null, negative savings preserved',()=>{const w=empty();w.assumptions.setupCost=0;const d=derive(w);assert.equal(d.coverage,null);assert.equal(d.roi,null);assert.equal(d.total,0);const s=sample();s.assumptions.assistedMinutes=100;assert.ok(derive(s).savedHours<0);assert.equal(derive(sample()).netValue,-760);});
test('required fields, enum, bounds, duplicates, invalid date and acceptance rejected',()=>{for(const change of [w=>delete w.records[0].owner,w=>w.records[0].evidence='unknown',w=>w.records[0].likelihood=0,w=>w.records[1].id='V01',w=>w.asOf='2026-02-30',w=>w.records[0].treatment='accept',w=>w.records[0].ai='false']){const w=sample();change(w);assert.throws(()=>validate(w));}const w=sample();w.records=Array.from({length:251},()=>w.records[0]);assert.throws(()=>validate(w),/250/);assert.throws(()=>parseInput(' '.repeat(10000001),'a.json'),/10 MB/);});
test('memo exposes decisions, score assumptions and claim/control/evidence join',()=>{const text=memo(sample(),'Customer assurance');assert.match(text,/IAM-01/);assert.match(text,/EV-IAM-012/);assert.match(text,/− evidence credit/);assert.match(text,/not achieved savings/);assert.equal(FIELDS.length,30);});
test('AI evaluation metric excludes supplier whose AI flag was removed',()=>{const w=sample();const before=derive(w);w.records[0].ai=false;const after=derive(validate(w));assert.equal(after.evalTotal,before.evalTotal-24);assert.equal(after.evalFailed,before.evalFailed-5);});

test('maximum allowed editable state can export and reimport',()=>{const w=sample();const r=w.records[0];w.records=Array.from({length:250},(_,i)=>({...r,id:'R'+i,parentVendorId:'',name:'界'.repeat(300),owner:'界'.repeat(300),service:'界'.repeat(300),rationale:'界'.repeat(300),question:'界'.repeat(300),evidenceRef:'界'.repeat(300),controlId:'界'.repeat(300),reviewer:'界'.repeat(300)}));const valid=validate(w);assert.deepEqual(parseInput(JSON.stringify(valid,null,2),'workspace.json'),valid);});
