import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {validate,metrics,derived,serialize}from '../../site/assets/suite-core.mjs';
const c=JSON.parse(fs.readFileSync(new URL('../../content/suite-catalog.json',import.meta.url)));
const d=records=>({version:1,records});
test('all 13 domains and 103 catalog views resolve typed entities',()=>{assert.equal(new Set(c.views.map(v=>v.domain)).size,13);assert.equal(c.views.length,103);for(const v of c.views)assert.ok(v.entity==='all'||c.entities[v.entity]);});
test('crossreferences and cycles are enforced',()=>{assert.throws(()=>validate(d([{type:'risk',id:'R',title:'Risk',vendorId:'missing'}]),c));assert.throws(()=>validate(d([{type:'vendor',id:'A',title:'A',parentVendorId:'B'},{type:'vendor',id:'B',title:'B',parentVendorId:'A'}]),c));});
test('evidence must be current and reviewed to count coverage',()=>{const records=[{type:'control',id:'C',title:'Control'},{type:'test',id:'T',title:'Test',controlId:'C',result:'Pass',evidenceURL:'https://example.org/evidence',reviewer:'Owner',testedDate:'2026-09-01',expiresDate:'2026-09-30'}];validate(d(records),c);assert.equal(metrics(records,'2026-09-28').coverage,100);assert.equal(metrics(records,'2026-10-01').coverage,0);assert.throws(()=>validate(d([{...records[1],reviewer:''},records[0]]),c));});
test('risk residual is explicit and threshold denominators are bounded',()=>{assert.match(derived({type:'risk',likelihood:5,impact:4,residualLikelihood:2,residualImpact:3},[]),/20.*6/);assert.equal(derived({type:'ai',evaluationTotal:0,evaluationFailed:0},[]),'Evaluation failures —');assert.throws(()=>validate(d([{type:'ai',id:'A',title:'AI',evaluationTotal:2,evaluationFailed:3}]),c));});
test('invalid dates unknown fields and status rejected',()=>{for(const change of [{reviewDate:'2026-02-30'},{status:'Certified'},{unexpected:'x'}])assert.throws(()=>validate(d([{type:'control',id:'C',title:'C',...change}]),c));});
test('JSON roundtrip preserves record types and data',()=>{const x=d([{type:'metric',id:'M',title:'Latency',value:5,threshold:4,direction:'At most'}]);assert.deepEqual(validate(JSON.parse(JSON.stringify(x)),c),x);assert.equal(derived(x.records[0],[]),'Threshold breached');});

test('compact export remains within import capacity near 20 MB',()=>{const records=Array.from({length:4900},(_,i)=>({type:'control',id:'C'+i,title:'Control '+i,notes:'x'.repeat(4000)}));const state=validate(d(records),c);const json=serialize(state);assert.ok(Buffer.byteLength(json)<=20*1024*1024);assert.equal(validate(JSON.parse(json),c).records.length,4900);});
test('entity calculations join obligations controls tests and dated issues',()=>{const rs=[{type:'obligation',id:'O',title:'Requirement'},{type:'control',id:'C',title:'Control',obligationId:'O'},{type:'test',id:'T',title:'Evidence',controlId:'C',result:'Pass',testedDate:'2026-09-01',expiresDate:'2026-09-30'}];assert.equal(derived(rs[0],rs),'Mapped controls 1');assert.equal(derived(rs[1],rs,'2026-09-28'),'Tests 1 · Current passes 1');assert.equal(derived(rs[1],rs,'2026-10-01'),'Tests 1 · Current passes 0');assert.equal(derived({type:'issue',openedDate:'2026-09-01'},[],'2026-09-28'),'Age 27 days');});
test('5000 linked vendors validate without repeated chain traversal',()=>{const records=Array.from({length:5000},(_,i)=>({type:'vendor',id:'V'+i,title:'Vendor '+i,...(i<4999?{parentVendorId:'V'+(i+1)}:{})}));assert.equal(validate(d(records),c).records.length,5000);records[4999].parentVendorId='V0';assert.throws(()=>validate(d(records),c),/Circular dependency/);});
test('threshold verdict needs explicit direction and processing completeness excludes null',()=>{assert.equal(derived({type:'metric',value:8,threshold:4},[]),'—');assert.equal(derived({type:'contract',slaActual:8,slaTarget:4,direction:''},[]),'—');assert.equal(derived({type:'processing',purpose:null,lawfulBasis:'',dataCategories:null,retentionDays:0},[]),'Defined fields 1/5');});
test('passing evidence rejects malformed URL and blank reviewer',()=>{const control={type:'control',id:'C',title:'Control'};const t={type:'test',id:'T',title:'Test',controlId:'C',result:'Pass',evidenceURL:'https://example.org/evidence',reviewer:'Owner',testedDate:'2026-09-28'};for(const change of [{evidenceURL:'https://'},{evidenceURL:'https://?bad'},{evidenceURL:'javascript:alert(1)'},{reviewer:'   '}])assert.throws(()=>validate(d([control,{...t,...change}]),c));assert.equal(validate(d([control,t]),c).records.length,2);});
