"""Build three executable synthetic delivery scenarios per registered domain."""
import json
from html import escape as e

def generate(root):
 configs=json.loads((root/'content/domain-reviews.json').read_text())
 catalog=json.loads((root/'content/suite-catalog.json').read_text())
 example=json.loads((root/'site/data/connected-scenario.json').read_text())
 (root/'server/scenario-definitions.mjs').write_text('// Generated from the canonical domain and record catalogs.\nexport const configs='+json.dumps(configs)+';\nexport const catalog='+json.dumps(catalog)+';\n')
 cards=[];index=[]
 for n,c in enumerate(configs,1):
  for variant in range(1,4):
   passed=variant==2;mode=c['assessment']['mode']
   population,baseline=(10,10 if passed else 4 if variant==1 else 7) if mode=='coverage' else (0 if passed else 8 if variant==1 else 12,5)
   if mode=='deadline':population,baseline=(12 if passed else 80 if variant==1 else 96,72)
   if mode=='recovery':population,baseline=(45 if passed else 120 if variant==1 else 180,60)
   scenario_id=f'D{n:02d}-{variant}'
   contexts={1:'AI supplier onboarding: unverified subprocessors, missing DPIA review and unclear retention. '+c['assessment']['action'],2:'Annual cloud assurance preparation: scoped controls and recorded passing tests are complete. '+c['assessment']['acceptance'],3:'Unapproved generative AI handles customer PII across borders: map flows, establish transfer safeguards and assign corrective actions. '+c['assessment']['action']}
   review=dict(scope='Synthetic '+c['title']+' review',owner='Example '+c['entity']+' owner',reviewer='Example accountable reviewer',evidenceURL='https://example.com/evidence/'+scenario_id,expires='2027-01-31',asOf='2026-10-09',checks=[passed]*len(c['checks']),domainInputs=dict(population=population,baseline=baseline,approval='Confirmed' if passed else 'Pending review'))
   # Domain-owned register records and typed links are preserved, never flattened into the lab schema.
   obligation=dict(type='obligation',id=scenario_id+'-OB',title=c['title']+' applicability review',domainSlug='regulatory-obligations',framework='; '.join(c['frameworks']),requirement=c['checks'][0])
   control=dict(type='control',id=scenario_id+'-CT',title=c['assessment']['deliverable'],domainSlug=c['slug'],owner=review['owner'],obligationId=obligation['id'],effectiveness='Effective' if passed else 'Untested')
   test=dict(type='test',id=scenario_id+'-TS',title='Synthetic '+c['title']+' evidence test',domainSlug='audit-readiness',controlId=control['id'],result='Pass' if passed else 'Not tested',evidenceURL=review['evidenceURL'] if passed else '',reviewer=review['reviewer'] if passed else '',testedDate='2026-10-09' if passed else '',expiresDate='2027-01-31' if passed else '')
   # Use catalog's precise enumerations rather than guessed test labels.
   if not passed:test['result']=next(x for x in catalog['entities']['test']['result'] if x!='Pass')
   records=[obligation,control,test]
   vendor=dict(type='vendor',id=scenario_id+'-VD',title='Example AI supplier',domainSlug='vendor-risk',service='LLM support processing',usesAI=not passed,reviewOutcome='Approve' if passed else 'Pending',owner='Example supplier reviewer',notes='Synthetic: subprocessors reviewed' if passed else 'Synthetic: subprocessors unverified; retention unclear')
   records.append(vendor)
   entity=c['entity']
   detail={
    'policy':dict(version='1.0',approver='Example policy reviewer',attested=baseline if mode=='coverage' else 0,requiredAttestations=population if mode=='coverage' else 10),
    'audit':dict(scope=review['scope'],populationSize=population if mode=='coverage' else 10,testedCount=baseline if mode=='coverage' else 0,selectionMethod='Declared synthetic sample'),
    'processing':dict(purpose='LLM support / customer PII',lawfulBasis='Declared; requires privacy validation' if passed else '',dataCategories='Customer PII',retentionDays=30 if passed else 0,transferMechanism='Declared SCC review complete' if passed else '',vendorId=vendor['id']),
    'ai':dict(purpose='Customer support assistant',vendorId=vendor['id'],oversightOwner='Example AI reviewer',classification='Transparency review',evaluationTotal=20,evaluationFailed=0 if passed else 3,releaseDecision='Review' if passed else 'Hold',transparencyEvidence=review['evidenceURL'] if passed else ''),
    'metric':dict(definition=c['assessment']['fields'][0]['label'],value=population,threshold=baseline,direction='At most',unit='Declared domain unit',measuredDate=review['asOf']),
    'asset':dict(criticality=4,vendorId=vendor['id'],vulnerability='' if passed else 'Declared baseline exception',patchStatus='Applied' if passed else 'Pending'),
    'contract':dict(vendorId=vendor['id'],clause=c['checks'][0],slaActual=population,slaTarget=baseline,direction='At most',unit='Declared domain unit'),
    'decision':dict(accountable=review['owner'],responsible=review['reviewer'],consulted='Example privacy and security reviewers',informed='Example audit lead',rationale=c['assessment']['action']),
    'risk':dict(category=c['title'],likelihood=2 if passed else 4,impact=2 if passed else 4,treatment='Reduce',vendorId=vendor['id']),
    'assessment':dict(dimension=c['title'],currentLevel=5 if passed else 2,targetLevel=5,rationale=c['assessment']['action']),
    'initiative':dict(objective=c['assessment']['deliverable'],progressPercent=100 if passed else 40),
    'issue':dict(category=c['title'],severity='Low' if passed else 'High',status='Closed' if passed else 'Open',controlId=control['id'],openedDate='2026-10-09',correctiveAction=c['assessment']['action'])
   }.get(entity,{})
   if entity not in ['control','test','obligation','vendor']:
    records.append(dict(type=entity,id=scenario_id+'-DM',title=c['assessment']['deliverable']+' source record',domainSlug=c['slug'],owner=review['owner'],notes='Synthetic domain-specific inputs',**detail))
   if not passed:records.append(dict(type='issue',id=scenario_id+'-AC',title='Review prerequisites before release',domainSlug='remediation',owner=review['reviewer'],status='Open',controlId=control['id'],openedDate='2026-10-09',severity='High',correctiveAction=c['assessment']['action']))
   base=dict(id=scenario_id+'-AI',name='Example LLM support supplier' if variant==1 else 'Example cloud assurance service' if passed else 'Example shadow AI service',owner='Example service owner',service='Customer support' if variant==1 else 'Cloud assurance' if passed else 'Cross-border PII processing',criticality='high',dataSensitivity='personal',ai=not passed,approved=passed,processor=True,region='EEA' if passed else 'US',dpa=passed,transfer=passed,disclosure='tested' if passed else 'gap',oversight='tested' if passed else 'assigned',evidence='current' if passed else 'missing',likelihood=2 if passed else 4 if variant==1 else 3,impact=2 if passed else 4,treatment='mitigate',reviewer=review['reviewer'] if passed else '',rationale='Synthetic metadata only',parentVendorId='',controlId=control['id'],evidenceRef=review['evidenceURL'] if passed else '',testOutcome='pass' if passed else 'not-tested',evidenceReviewedAt='2026-10-09' if passed else '',evidenceExpiresAt='2027-01-31' if passed else '',question=c['checks'][0][:300],aiEvalTotal=0 if passed else 20,aiEvalFailed=0 if passed else 3,techniqueId='' if passed else 'AML.T0051')
   payload=dict(scenarioVersion=1,id=scenario_id,domain=c['slug'],title=['AI supplier onboarding','Recorded audit readiness','Cross-border AI incident'][variant-1]+' — '+c['title'],context=contexts[variant],reviewInputs=review,workspace=dict(version=1,records=records,updatedAt=None),decisionLab=dict(schemaVersion='1.0',asOf='2026-10-09',provenance='Synthetic scenario; evidence and passing tests are illustrative assertions',assumptions=dict(manualMinutes=0,assistedMinutes=0,hourlyCost=0,setupCost=0),records=[base]))
   if variant==3:payload['incident']=dict(awareAt='2026-10-09T09:00:00Z',deadlineHours=72,reportingRequired=True)
   path=f'/samples/{c["slug"]}/{variant}.json';dest=root/'site'/path.lstrip('/');dest.parent.mkdir(parents=True,exist_ok=True);dest.write_text(json.dumps(payload,indent=2)+'\n')
   entry=dict(id=scenario_id,domain=c['slug'],title=payload['title'],url=path,context=contexts[variant],expectedGate='Ready for accountable review' if passed else 'Hold pending evidence and review',deliverable=c['assessment']['deliverable'],method=mode)
   index.append(entry)
  cards.append('<article class="card"><p class="eyebrow">'+f'D{n:02d}'+'</p><h2><a href="/work/'+c['slug']+'/">'+e(c['title'])+'</a></h2><p>'+e(c['assessment']['deliverable'])+'</p>'+''.join('<p><a download href="'+x['url']+'">Download '+e(x['title'].split(' — ')[0])+' JSON →</a></p>' for x in index[-3:])+'</article>')
 (root/'site/data/scenarios.json').write_text(json.dumps(index,indent=2)+'\n')
 shell=(root/'site/enterprise/index.html').read_text();start=shell.index('<main');end=shell.index('</main>')+len('</main>')
 body='<main id="main" class="wrap"><section class="hero"><p class="eyebrow">Executable delivery scenarios</p><h1>'+str(len(index))+' scenarios. '+str(len(configs))+' connected domains.</h1><p>Inspect the decision inputs, reproduce the calculation and export a review package. Synthetic data demonstrates behavior; it is not client evidence.</p><ol><li>Download one domain scenario below.</li><li>Import it into its domain review, <a href="/workspace/">Workspace</a> or <a href="/decision-lab/">Decision Lab</a>. A scenario contains separate version-1 typed records and schema-1.0 supplier records.</li><li>Inspect the domain-specific calculation, gate, source records and cross-domain links.</li><li>Export the version-2 scenario decision pack or Markdown memo. Native register exports remain separate.</li></ol><p><a href="/docs/#executable-scenarios">Calculation and demonstration guide →</a></p></section><section class="grid">'+''.join(cards)+'</section></main>'
 dest=root/'site/samples/index.html';dest.parent.mkdir(exist_ok=True);dest.write_text(shell[:start]+body+shell[end:])

 # Curated client walkthrough sits above the 87 reusable synthetic cases; all three
 # selected files are generated from the same canonical domain records and validators.
 featured=[
  ('D14-1','AI vendor onboarding','/samples/ai-governance/1.json','AI disclosure, processor terms and release gate','AI / THIRD-PARTY RISK'),
  ('D07-2','Audit readiness pass','/samples/audit-readiness/2.json','Recorded passing tests and evidence metadata','SOC 2 / ISO 27001'),
  ('D12-3','Cross-border AI incident','/samples/processor-governance/3.json','Transfer safeguards, owner actions and conditional reporting clock','PRIVACY / INCIDENT')
 ]
 featured_cards=''.join('<article class="outcome-card"><p class="eyebrow">'+e(tag)+'</p><h2>'+e(title)+'</h2><p>'+e(summary)+'</p><div class="actions"><button type="button" data-outcome-select="'+e(sid)+'">Run scenario →</button><a href="'+url+'" download>Download JSON ↓</a></div></article>' for sid,title,url,summary,tag in featured)
 outcomes_main='''<main id="main" class="wrap outcomes">
 <section class="hero outcomes-hero"><p class="eyebrow">The finished work, not another software seat</p><h1>Resolve governance bottlenecks.<br><em>See the decision before you buy.</em></h1><p class="lead">Three executable client-style scenarios demonstrate bounded AI supplier reviews, control-evidence readiness, and cross-border incident triage. Each has real calculation logic, synthetic source records and an exportable decision memo.</p><div class="actions"><a class="button primary" href="#scenarios">Try a review →</a><a href="https://aaowasi.pages.dev/contact/">Scope a finished review pack ↗</a></div><p class="small">Human-reviewed deliverables, scoped per engagement. No hourly retainer or guaranteed compliance result implied. Prices quoted after agreeing evidence and acceptance criteria.</p></section>
 <section class="section"><p class="eyebrow">Productized governance service</p><h2>Pay for a completed, reviewable output.</h2><div class="outcomes-flow"><div><strong>01 / Send metadata</strong><p>Agree the decision, in-scope systems, named owners and permissible evidence references.</p></div><div><strong>02 / Compute &amp; inspect</strong><p>Deterministic checks propose a risk band, evidence gaps and review queue; any AI assistance is subject to human validation.</p></div><div><strong>03 / Receive the pack</strong><p>Receive versioned findings, treatment actions and a decision memo. Approval or regulatory conclusions remain with authorized reviewers.</p></div></div></section>
 <section class="section" id="scenarios"><p class="eyebrow">Interactive delivery proof · synthetic fixtures</p><h2>Three scenarios. Three different outcomes.</h2><p>Download the exact JSON shown below, inspect the decision and import that same file into either linked register. The separate typed workspace and Decision Lab formats are validated from one scenario envelope.</p><div class="outcome-grid">'''+featured_cards+'''</div>
 <div class="outcome-console" id="outcome-console"><div class="outcome-console-head"><div><span class="eyebrow">DECISION ENGINE / SNAPSHOT</span><h3 id="outcome-title">Choose a scenario</h3></div><strong id="outcome-gate">AWAITING INPUT</strong></div><p id="outcome-status" role="status" aria-live="polite">Select a sample to calculate its recorded review outcome.</p><div class="outcome-stats"><div><span>Recorded checks</span><strong id="outcome-readiness">—</strong></div><div><span>Tested control coverage</span><strong id="outcome-coverage">—</strong></div><div><span>High-priority records (≥16)</span><strong id="outcome-high">—</strong></div><div><span>Deadline candidate (UTC)</span><strong id="outcome-deadline">—</strong></div></div><h4>Evidence gaps &amp; owner actions</h4><ul id="outcome-actions"></ul><p class="small" id="outcome-basis"></p><details><summary>Inspect the version-2 decision payload</summary><pre class="review-json" id="outcome-json"></pre></details><div class="actions"><button id="outcome-export-json" type="button" disabled>Export Decision Pack v2 ↓</button><button id="outcome-export-memo" type="button" disabled>Export memo ↓</button><a href="/workspace/">Open 29-domain Workspace →</a><a href="/decision-lab/">Open Decision Lab →</a></div><label>Or import a scenario JSON file to review locally<input id="outcome-upload" type="file" accept=".json,application/json"></label></div></section>
 <section class="section"><h2>Global applicability requires verified rules, not a fake live ticker.</h2><p>The model links an obligation to its evidence, jurisdiction, publication date and accountable reviewer. This demonstration does not assert automatic coverage of 190 countries or feed updates it cannot verify. A regulatory change remains pending until an authorized reviewer confirms applicability.</p><p>Primary legal references: <a href="https://ai-act-service-desk.ec.europa.eu/en/ai-act/article-50">EU AI Act Article 50 ↗</a> · <a href="https://www.edpb.europa.eu/topics/security-data-breaches/personal-data-breaches_en">EDPB breach notification ↗</a> · <a href="https://sequoiacap.com/article/services-the-new-software">Sequoia’s outcome-based service thesis ↗</a>.</p><p><a href="/samples/">Explore all 87 synthetic domain fixtures →</a> · <a href="/docs/">Operating documentation →</a></p></section></main>'''
 outcomes_shell=shell[:start]+outcomes_main+shell[end:]
 outcomes_shell=outcomes_shell.replace('</head>','<link rel="stylesheet" href="/assets/outcomes.css"><script type="module" src="/assets/outcomes.mjs"></script></head>')
 outdir=root/'site/outcomes';outdir.mkdir(parents=True,exist_ok=True);(outdir/'index.html').write_text(outcomes_shell)

