from pathlib import Path
import json,shutil
ROOT=Path(__file__).resolve().parents[1]
from domain_build import render_domains
render_domains(ROOT)
shutil.copyfile(ROOT/'content/domain-reviews.json',ROOT/'site/data/domain-reviews.json')

from build_delivery import render as render_delivery
snapshot=json.loads((ROOT/'content/verified-delivery.json').read_text())
page=(ROOT/'templates/results.html').read_text().replace('{{DELIVERY_EVIDENCE}}',render_delivery(snapshot))
(ROOT/'site/results').mkdir(exist_ok=True)
(ROOT/'site/results/index.html').write_text(page)
shutil.copyfile(ROOT/'content/verified-delivery.json',ROOT/'site/data/verified-delivery.json')

(ROOT/'site/suite').mkdir(exist_ok=True)
# Suite and workspace are generated by domain_build
shutil.copyfile(ROOT/'content/suite-catalog.json', ROOT/'site/data/suite-catalog.json')

(ROOT/'site/evaluate').mkdir(exist_ok=True)
shutil.copyfile(ROOT/'templates/evaluate.html',ROOT/'site/evaluate/index.html')

from page_sections import split_projects
split_projects(ROOT)

(ROOT/'site/architecture').mkdir(exist_ok=True)
from build_architecture import render_architecture
(ROOT/'site/architecture/index.html').write_text(render_architecture(ROOT))
shutil.copyfile(ROOT/'content/domain-matrix.json',ROOT/'site/data/domain-matrix.json')

# Keep all domain counts sourced from catalogue data.
for page in (ROOT/'site').rglob('*.html'):
 page.write_text(page.read_text().replace('{{DOMAIN_COUNT}}',str(len(json.loads((ROOT/'content/projects.json').read_text())))))
from build_docs import generate
generate(ROOT)
from seo import apply_seo
apply_seo(ROOT)
